"""columns forma and metodo de pago changed to Order table 

Revision ID: 5349cbfd600a
Revises: de8ddea876b5
Create Date: 2024-07-22 13:20:17.601128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5349cbfd600a'
down_revision = 'de8ddea876b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.drop_column('metodo_de_pago')
        batch_op.drop_column('forma_de_pago')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_de_pago', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('metodo_de_pago', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('metodo_de_pago')
        batch_op.drop_column('forma_de_pago')

    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_de_pago', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('metodo_de_pago', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
