"""add tracking numer column to Order table

Revision ID: 5563c6a25335
Revises: 705c7dfd497a
Create Date: 2024-07-31 11:57:51.860838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5563c6a25335'
down_revision = '705c7dfd497a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('tracking_number')

    # ### end Alembic commands ###
