"""add phone nulleable column to Client table 

Revision ID: 705c7dfd497a
Revises: 59bb00f4fe93
Create Date: 2024-07-29 10:48:57.640902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705c7dfd497a'
down_revision = '59bb00f4fe93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
