"""Add columns cp, forma de pago, metodo to Billing table 

Revision ID: de8ddea876b5
Revises: eddea97175dd
Create Date: 2024-07-22 10:50:49.839464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8ddea876b5'
down_revision = 'eddea97175dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cp', sa.String(length=5), nullable=False))
        batch_op.add_column(sa.Column('forma_de_pago', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('metodo_de_pago', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.drop_column('metodo_de_pago')
        batch_op.drop_column('forma_de_pago')
        batch_op.drop_column('cp')

    # ### end Alembic commands ###
